Program = (Statement ";")*

Statement =
  Expression
  | Binding

Expression =
  "(" Expression ")"
  | "\\" (Identifier)+ "->" Expression
  | (Identifier)*
  | Literal

Binding = "let" Identifier ":" Type "=" Expression

Identifier = [\S\D]\S*

Type =
  PrimitiveType "->" Type
  | PrimitiveType

PrimitiveType =
  "Real"
  | "Unit"
  | "Void"

Literal =
  Number
  "Unit"

Number = ("0" | [1-9] [0-9]*)("." [0-9]+ )?
